import { writeFileSync } from "node:fs";
import { toSarif } from "./sarif.js";
import type { Finding, ReviewResult } from "./types.js";

const SEVERITY_ORDER = ["blocker", "high", "medium", "low"] as const;
const REPO_URL = "https://github.com/simhanson123/signal-lens";

function sortFindings(findings: Finding[]): Finding[] {
  return [...findings].sort((a, b) => {
    const severityDiff =
      SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity);
    if (severityDiff !== 0) return severityDiff;
    return b.confidence - a.confidence;
  });
}

export function toMarkdown(result: ReviewResult): string {
  const findings = sortFindings(result.findings);
  const lines: string[] = [];

  lines.push("## Signal Lens Report");
  lines.push("");
  lines.push(`**Base:** \`${result.base}\` → **Head:** \`${result.head}\``);
  lines.push(`**Generated:** ${result.generatedAt}`);
  lines.push(`**Mode:** ${result.metadata.staticOnly ? "static analysis" : "static + AI"}`);
  if (result.metadata.provider) lines.push(`**Provider:** ${result.metadata.provider}`);
  if (result.pr?.title) lines.push(`**PR:** ${result.pr.title}`);
  if (result.summary.ciStatus) lines.push(`**CI:** ${result.summary.ciStatus}`);
  if (result.metadata.aiSkipReason) {
    lines.push(`**AI:** ${result.metadata.aiReview} — ${result.metadata.aiSkipReason}`);
  }
  lines.push("");

  lines.push("### Summary");
  lines.push(`- **Purpose:** ${result.summary.purpose}`);
  lines.push(`- **Scope:** ${result.summary.scope}`);
  lines.push(
    result.summary.riskFiles.length > 0
      ? `- **Risk files:** ${result.summary.riskFiles.map((f) => `\`${f}\``).join(", ")}`
      : "- **Risk files:** none flagged"
  );
  lines.push("");

  if (findings.length === 0) {
    lines.push("### Findings");
    lines.push("");
    lines.push("No issues detected.");
    if (result.metadata.aiReview === "skipped") {
      lines.push(`> AI review skipped: ${result.metadata.aiSkipReason}`);
    }
    return lines.join("\n");
  }

  lines.push(`### Findings (${findings.length})`);
  lines.push("");

  for (const finding of findings) {
    lines.push(`#### ${severityBadge(finding.severity)} ${finding.title}`);
    lines.push("");
    lines.push(`**ID:** \`${finding.id}\` | **Category:** ${finding.category} | **Confidence:** ${Math.round(finding.confidence * 100)}%`);
    lines.push("");
    lines.push(finding.reason);
    lines.push("");

    if (finding.evidence.length > 0) {
      lines.push("**Evidence:**");
      for (const ev of finding.evidence) {
        const loc = ev.line ? `${ev.file}:${ev.line}` : ev.file;
        lines.push(`- \`${loc}\`${ev.symbol ? ` (${ev.symbol})` : ""}`);
        if (ev.snippet) lines.push(`  \`\`\`\n  ${ev.snippet.trim()}\n  \`\`\``);
      }
      lines.push("");
    }

    lines.push(`**Suggested action:** ${finding.suggestedAction}`);
    lines.push(`**Follow-up:** \`/signal-lens false-positive ${finding.id}\` | \`/signal-lens fix ${finding.id}\` | \`/signal-lens explain\``);
    if (finding.repro) {
      lines.push("");
      lines.push(`**Verify:** \`${finding.repro}\``);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by [Signal Lens](${REPO_URL})*`);

  return lines.join("\n");
}

function severityBadge(severity: Finding["severity"]): string {
  const map: Record<Finding["severity"], string> = {
    blocker: "🛑 BLOCKER",
    high: "🔴 HIGH",
    medium: "🟡 MEDIUM",
    low: "🔵 LOW",
  };
  return map[severity];
}

export function toJson(result: ReviewResult): string {
  return JSON.stringify(result, null, 2);
}

export function writeOutput(
  result: ReviewResult,
  format: "markdown" | "json" | "sarif" | "both" | "all",
  outputFile?: string
): { markdown?: string; json?: string; sarif?: string } {
  const markdown = format === "markdown" || format === "both" || format === "all" ? toMarkdown(result) : undefined;
  const json = format === "json" || format === "both" || format === "all" ? toJson(result) : undefined;
  const sarif = format === "sarif" || format === "all" ? toSarif(result) : undefined;

  if (outputFile) {
    const base = outputFile.replace(/\.[^.]+$/, "");
    if (format === "json") writeFileSync(outputFile, json!, "utf-8");
    else if (format === "markdown") writeFileSync(outputFile, markdown!, "utf-8");
    else if (format === "sarif") writeFileSync(outputFile, sarif!, "utf-8");
    else if (format === "both") {
      writeFileSync(`${base}.md`, markdown!, "utf-8");
      writeFileSync(`${base}.json`, json!, "utf-8");
    } else if (format === "all") {
      writeFileSync(`${base}.md`, markdown!, "utf-8");
      writeFileSync(`${base}.json`, json!, "utf-8");
      writeFileSync(`${base}.sarif`, sarif!, "utf-8");
    }
  }

  return { markdown, json, sarif };
}