import { writeFileSync } from "node:fs";
import type { Finding, ReviewResult } from "./types.js";

const SEVERITY_ORDER = ["blocker", "high", "medium", "low"] as const;

function sortFindings(findings: Finding[]): Finding[] {
  return [...findings].sort((a, b) => {
    const severityDiff =
      SEVERITY_ORDER.indexOf(a.severity) - SEVERITY_ORDER.indexOf(b.severity);
    if (severityDiff !== 0) return severityDiff;
    return b.confidence - a.confidence;
  });
}

export function toMarkdown(result: ReviewResult): string {
  const findings = sortFindings(result.findings);
  const lines: string[] = [];

  lines.push("## review-mcp Report");
  lines.push("");
  lines.push(`**Base:** \`${result.base}\` → **Head:** \`${result.head}\``);
  lines.push(`**Generated:** ${result.generatedAt}`);
  lines.push("");

  lines.push("### Summary");
  lines.push(`- **Purpose:** ${result.summary.purpose}`);
  lines.push(`- **Scope:** ${result.summary.scope}`);
  if (result.summary.riskFiles.length > 0) {
    lines.push(`- **Risk files:** ${result.summary.riskFiles.map((f) => `\`${f}\``).join(", ")}`);
  } else {
    lines.push("- **Risk files:** none flagged");
  }
  lines.push("");

  if (findings.length === 0) {
    lines.push("### Findings");
    lines.push("");
    lines.push("No issues detected by static analyzers.");
    lines.push("");
    lines.push("> AI-powered deep review requires `OPENAI_API_KEY` (v0.1+). Static analysis completed successfully.");
    return lines.join("\n");
  }

  lines.push(`### Findings (${findings.length})`);
  lines.push("");

  for (const finding of findings) {
    const badge = severityBadge(finding.severity);
    lines.push(`#### ${badge} ${finding.title}`);
    lines.push("");
    lines.push(`**Category:** ${finding.category} | **Confidence:** ${Math.round(finding.confidence * 100)}%`);
    lines.push("");
    lines.push(finding.reason);
    lines.push("");

    if (finding.evidence.length > 0) {
      lines.push("**Evidence:**");
      for (const ev of finding.evidence) {
        const loc = ev.line ? `${ev.file}:${ev.line}` : ev.file;
        lines.push(`- \`${loc}\`${ev.symbol ? ` (${ev.symbol})` : ""}`);
        if (ev.snippet) {
          lines.push(`  \`\`\`\n  ${ev.snippet.trim()}\n  \`\`\``);
        }
      }
      lines.push("");
    }

    lines.push(`**Suggested action:** ${finding.suggestedAction}`);
    if (finding.repro) {
      lines.push("");
      lines.push(`**Verify:** \`${finding.repro}\``);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("*Generated by [review-mcp](https://github.com/review-mcp/review-mcp)*");

  return lines.join("\n");
}

function severityBadge(severity: Finding["severity"]): string {
  const map: Record<Finding["severity"], string> = {
    blocker: "🛑 BLOCKER",
    high: "🔴 HIGH",
    medium: "🟡 MEDIUM",
    low: "🔵 LOW",
  };
  return map[severity];
}

export function toJson(result: ReviewResult): string {
  return JSON.stringify(result, null, 2);
}

export function writeOutput(
  result: ReviewResult,
  format: "markdown" | "json" | "both",
  outputFile?: string
): { markdown?: string; json?: string } {
  const markdown = format === "markdown" || format === "both" ? toMarkdown(result) : undefined;
  const json = format === "json" || format === "both" ? toJson(result) : undefined;

  if (outputFile) {
    if (format === "json") {
      writeFileSync(outputFile, json!, "utf-8");
    } else if (format === "markdown") {
      writeFileSync(outputFile, markdown!, "utf-8");
    } else {
      const base = outputFile.replace(/\.[^.]+$/, "");
      writeFileSync(`${base}.md`, markdown!, "utf-8");
      writeFileSync(`${base}.json`, json!, "utf-8");
    }
  }

  return { markdown, json };
}