import type { ChangedFile, Finding, ReviewResult } from "./types.js";

const REPO_URL = "https://github.com/simhanson123/signal-lens";

export function toWalkthrough(result: ReviewResult): string {
  const lines: string[] = [];
  const files = result.changedFiles ?? [];
  const findings = result.findings;

  const totalAdditions = files.reduce((n, f) => n + f.additions, 0);
  const totalDeletions = files.reduce((n, f) => n + f.deletions, 0);

  lines.push("## Signal Lens Walkthrough");
  lines.push("");

  lines.push(
    `**${files.length} file(s) changed**:` +
    ` +${totalAdditions} −${totalDeletions}` +
    ` | **${findings.length} finding(s)**` +
    `${result.metadata.aiReview !== "completed" ? ` | AI: ${result.metadata.aiReview}` : ""}`
  );
  lines.push("");

  const riskLevel = assessRisk(findings);
  lines.push(`**Risk level: ${riskLevel.badge} ${riskLevel.label}**`);
  if (riskLevel.note) lines.push(`> ${riskLevel.note}`);
  lines.push("");

  if (files.length > 0) {
    lines.push("### Changes by area");
    lines.push("");
    const byCategory = groupByCategory(files);
    for (const [category, fileList] of byCategory) {
      lines.push(`**${category}** (${fileList.length})`);
      for (const f of fileList.slice(0, 8)) {
        const change = formatChange(f);
        lines.push(`- \`${f.path}\` ${change}`);
      }
      if (fileList.length > 8) {
        lines.push(`- ... and ${fileList.length - 8} more`);
      }
      lines.push("");
    }
  }

  const keyFindings = findings
    .filter((f) => f.severity === "blocker" || f.severity === "high")
    .slice(0, 5);

  if (keyFindings.length > 0) {
    lines.push("### Key findings");
    lines.push("");
    for (const f of keyFindings) {
      const icon = f.severity === "blocker" ? "🛑" : "🔴";
      const loc = f.evidence[0]
        ? ` \`${f.evidence[0].file}${f.evidence[0].line ? `:${f.evidence[0].line}` : ""}\``
        : "";
      lines.push(`- ${icon} **${f.title}**${loc}`);
    }
    lines.push("");
  }

  lines.push("---");
  if (findings.length > keyFindings.length) {
    lines.push(
      `*${findings.length - keyFindings.length} additional medium/low finding(s). ` +
      `Run \`signal-lens review\` for the full report.*`
    );
  }
  lines.push(`*Generated by [Signal Lens](${REPO_URL})*`);

  return lines.join("\n");
}

function assessRisk(findings: Finding[]): { badge: string; label: string; note?: string } {
  const blockers = findings.filter((f) => f.severity === "blocker").length;
  const highs = findings.filter((f) => f.severity === "high").length;

  if (blockers > 0) {
    return {
      badge: "🛑",
      label: "High",
      note: `${blockers} blocker(s) must be resolved before merging.`,
    };
  }
  if (highs > 0) {
    return {
      badge: "🔴",
      label: "Medium",
      note: `${highs} high-severity finding(s) need review.`,
    };
  }
  if (findings.length > 0) {
    return { badge: "🟡", label: "Low", note: `${findings.length} minor finding(s).` };
  }
  return { badge: "🟢", label: "Minimal" };
}

function groupByCategory(files: ChangedFile[]): Map<string, ChangedFile[]> {
  const map = new Map<string, ChangedFile[]>();
  for (const f of files) {
    const list = map.get(f.category) ?? [];
    list.push(f);
    map.set(f.category, list);
  }
  return map;
}

function formatChange(f: ChangedFile): string {
  const parts: string[] = [];
  if (f.additions > 0) parts.push(`+${f.additions}`);
  if (f.deletions > 0) parts.push(`−${f.deletions}`);
  if (f.status === "added") parts.push("(new)");
  else if (f.status === "deleted") parts.push("(deleted)");
  else if (f.status === "renamed") parts.push("(renamed)");
  return parts.join(" ");
}
